# Generated by Django 4.2.10 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFromVint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('crystals', models.IntegerField()),
                ('xcrystals', models.IntegerField()),
                ('experience', models.IntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
