# Generated by Django 4.2.10 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VintPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('player_id', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
